env:
  global:
  - BRANCH_TO_TEST=$TRAVIS_BRANCH
  - secure: "Fzd0DNiyQUzrsBGFrsXfW6KAbYEgCkPsVDFRLNh8RGZ/19cbQr0vAV9uphch1dQNlvSa7OJT6pysAVlbFrW0FBHgk5BWaWr4ufeB8Z+HixhVPrT37ilkVCMGt1GrABbe1Z3gqToORH7ebVHAMlnV6P5JlA2ffwfjK3bxlOj+l5co/NJx5l7CaelIYzmXnjE/U/xFcuvs98YLECBNAc7/MJiHcLCdi07kckFmAXWihMzUV5ot2V1Bq2Y4XnN4qQyvxJpMbS+/5Sw5iMrn4W5rt4Za7PUbgGvRXkJSdmPzQbx82vU9kbiZtAshMzNw96SNmdOS1uC/qBfq7D21vbuMOx/efdyHp8VzlV8uePjgIq34HUhv+x1nX/Ypr/fUrgLJ5OnU9JNeQjc1ubTyGbbl+mZMu3/5vUTreNkNJPi5X0ycvmGGy+auHBGzgxDzIO2oS5H4KKI5YmDO+mZiOEwpDgvQjmn3Jf+4d/42tG4SWnTej3bh/EpdrV0HYSxVBFZ1ue4bWqONPrpra3sssH1Vgi9OLhalAZGb1I1G0Wse1dMbJ60HkvOQW882DP53gYuK0QeJ4IwlZt7lNo1oBEUi/1zBD9nK4mOHRZ1tEzTwOTnDc2aZGr9yPYol//4RkaTzhNn4zyxayDxIsRZFCDcQdvg8UfnxJpPoBugBT5mSXs8="
  matrix:
  #- ADDRESS_MODEL=32
  - ADDRESS_MODEL=64
language: cpp
compiler:
- gcc
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python-yaml
    - valgrind
    - gcc-6
    - g++-6
    - gdb
    - xsltproc
    - docbook-xsl
    - doxygen
before_script:
    - PROJECT_TO_TEST=`basename $TRAVIS_BUILD_DIR`
    - cd $HOME
    - wget -O boost_1_64_0.tar.gz https://dl.bintray.com/boostorg/beta/1.64.0.rc.1/source/boost_1_64_0_rc1.tar.gz
    - tar -xf boost_1_64_0.tar.gz > /dev/null
    - BOOST=$HOME/boost_1_64_0
    - cd $BOOST
    - "./bootstrap.sh"
    - "./b2 headers"
    - cd $TRAVIS_BUILD_DIR
    - MW_TEST=$HOME/mw.test
    - git init $MW_TEST
    - cd $MW_TEST
    - if [ $BRANCH_TO_TEST = "master" ]; then
      MW_BRANCH=master; 
      else MW_BRANCH=develop; fi
    - git remote add --no-tags -t $MW_BRANCH origin https://github.com/mw-sc/mw.test.git
    - git fetch --depth=1
    - git checkout $MW_BRANCH
    - git submodule update --init --merge
    - git remote set-branches --add origin $MW_BRANCH
    - git pull --recurse-submodules
    - git submodule update --init
    - git checkout $MW_BRANCH
    - git submodule foreach "git reset --quiet --hard; git clean -fxd"
    - git reset --hard; git clean -fxd
    - git status
    - echo "Removing mw.calltrace"
    - rm -rf $MW_TEST/calltrace
    - mv $TRAVIS_BUILD_DIR/../$PROJECT_TO_TEST $MW_TEST/calltrace
    - cp user-config.travis.jam user-config.jam
    - cd ./calltrace/test
script:
- $BOOST/b2 -sBOOST_ROOT=$BOOST define=MW_TRAVISCI_BUILD toolset=gcc-6 linkflags="-ldl -pthread" -sBOOST_BUILD_PATH=. -j4 address-model=$ADDRESS_MODEL testing.launcher=valgrind valgrind=on cxxflags=--coverage cflags=--coverage linkflags=--coverage 
after_success:
    # Copying Coveralls data to a separate folder
    - mkdir -p ./coverals
    - find ../../bin.mw/calltrace -name *.gcda -exec cp "{}" ./coverals/ \;
    - find ../../bin.mw/calltrace -name *.gcno -exec cp "{}" ./coverals/ \;

    # Preparing Coveralls data by changind data format to a readable one
    - git clone https://github.com/linux-test-project/lcov.git lcov_dir
    - GCOV_VERSION="--gcov-tool gcov-6"
    - LCOV="$MW_TEST/calltrace/test/lcov_dir/bin/lcov $GCOV_VERSION --compat-libtool"
    - $LCOV --directory ./coverals --base-directory ./ --capture --output-file ./coverals/coverage.info
    - $LCOV --remove ./coverals/coverage.info "$MW_TEST/calltrace/test/*" "*boost*" "/usr/*" "$MW_TEST/libs/*" "$MW_TEST/dbg-runner/*" -o ./coverals/coverage.info

    # Sending data to Coveralls
    - gem install coveralls-lcov
    # https://github.com/okkez/coveralls-lcov/issues/2
    - coveralls-lcov  --source-encoding=ISO-8859-1 ./coverals/coverage.info
    - if [ $BRANCH_TO_TEST = "develop" ]; then 
         cd ../doc; $BOOST/b2 -j4 -sBOOST_ROOT=$BOOST linkflags="-ldl -pthread" -sBOOST_BUILD_PATH=.;
         git clone https://$GH_TOKEN@github.com/mw-sc/mw-sc.github.io.git -b master $HOME/pages > /dev/null 2>&1 ;
         cd html; cp -r * $HOME/pages/calltrace;
         cd $HOME/pages;
         git config user.email "travis@travis-ci.og";
         git config user.name "Travis";
         git commit -am "Updated calltrace documentation"; 
         git remote add origin-pages https://${GH_TOKEN}@github.com/mw-sc/mw-sc.github.io.git > /dev/null 2>&1;
         git push --quiet --set-upstream origin-pages master;
         fi 